config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end

  root 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses, :dependent => :destroy
  has_many :ingredients, through: :doses, :dependent => :destroy

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates_uniqueness_of :ingredient_id, :scope => [:cocktail_id]
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses
  has_many :cocktails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,100,183,0.1) 100%, rgba(0,30,100,0.4) 53%), url(<%= image_path "cocktail6.png"%>);">
  <div class="banner-content">
    <h1>Martini's</h1>
    <p>Find your best cocktails</p>
    <a class="btn btn-primary btn-lg">Find your cocktail</a>
  </div>
</div>


<h2>All your cocktails</h1>
<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-4">
    <% if cocktail.photo_url.nil? %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/dh46jpozr/image/upload/v1512142328/wkafbinqzkfooqq4ivmc.jpg')";>
        <% else %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>);">
    <% end %>
      <div class="card-category">
        <% if cocktail.ingredients.first %>
          <p> Main ingredient: <%= cocktail.ingredients.first.name %> </p>
        <% else %>
         <p> Does not have main ingredient </p>
         <% end %>
     </div>
      <div class="card-description">
        <h3><%= link_to cocktail.name, cocktail_path(cocktail), {:style=> 'color:#E0D3DE;' 'text-decoration:none'}%></h3>
      </div>
    </div>
    </div>
    <% end %>
  </div>
  <div class="add-cocktail">
  <%= link_to "Add a new cocktail", new_cocktail_path, class: "btn-medium" %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1> Add your cocktail here: </h1>
      <div class="form">
        <%= simple_form_for(@cocktail) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit class: "btn-medium" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
    <h2><%= @cocktail.name %></h2>
    <% if @cocktail.photo_url.nil? %>
    <%= cl_image_tag("wkafbinqzkfooqq4ivmc.jpg")%>
    <% else   %>
    <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
    <% end %>
    </div>
    <div class="col-xs-7 col-xs-offset-1" id="doses">
      <div class="description">
      <h3>Here are the doses of for <%= @cocktail.name %></h3>
      <ul>
      <% @cocktail.doses.each do |dose| %>
        <li><span> <%= dose.description %> </span> <%= dose.ingredient.name %>
         <%= link_to "Delete this dose", cocktail_dose_path(@cocktail, dose), method: :delete, class: "delete" %></li>
      <% end %>
      </ul>
      </div>
      <%= link_to "Delete this cocktail", cocktail_path(@cocktail), method: :delete, class: "btn-medium" %>
      <%= link_to "Go back to all cocktails", cocktails_path, class: "btn-medium"  %>
      <%= link_to "Add a dose", new_cocktail_dose_path(@cocktail), class: "btn-medium" %>
      </div>
  </div>
</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h1> Add the dose here: </h1>
    <div class="form">
    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.input :description %>
      <%= f.association :ingredient %>
      <%= f.submit %>
    <% end %>
    </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <%= yield %>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logo.jpg", {class: "img-circle", id: "logo"}%>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>


    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "avatar.jpg", {class: "img-circle avatar", id: "logo"}%>
      </div>
    </div>
  </div>
</div>